esphome:
  name: watch
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - light.turn_on: 
          id: led
          brightness: 100%
      - display.page.show: home_page
      - delay: 30s
      - light.turn_off: led
      
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
        CONFIG_ESP32_S3_BOX_BOARD: "y"
        CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
        CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
        CONFIG_TCPIP_RECVMBOX_SIZE: "512"
        CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: "Y"
        CONFIG_TCP_SND_BUF_DEFAULT: "65535"
        CONFIG_TCP_WND_DEFAULT: "512000"
        CONFIG_TCP_RECVMBOX_SIZE: "512"
  flash_size: 16MB
  
psram:
  mode: octal
  speed: 80MHz
  
logger:
  hardware_uart: uart0

api:
  on_client_connected:
    then:
      - pcf8563.read_time:
      - media_player.play_media: http://192.168.1.8:8123/local/api.mp3
            
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
                
time:
  - platform: pcf8563
    id: rtc_time
    i2c_id: general
    address: 0x51
    update_interval: never

  - platform: homeassistant
    on_time_sync:
      then:
        pcf8563.write_time:
      
i2c:
  - id: general
    sda: 10
    scl: 11
  - id: tsc
    sda: 39
    scl: 40
 
spi:
  - id: tft
    clk_pin: GPIO18
    mosi_pin: GPIO13
    interface: hardware
    
button:
  - platform: restart
    name: reboot
    id: rst_but

remote_transmitter:
  pin: 2
  carrier_duty_percent: 50%
  
external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: dev-next
    components: [ adf_pipeline, i2s_audio ]
    refresh: 0s  
    
adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_spk
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO46
    
  - platform: i2s_audio
    type: audio_in
    id: adf_mic
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO47
    channel: right
    sample_rate: 16000
    bits_per_sample: 16bit
    pdm: true

microphone:
  - platform: adf_pipeline
    id: adf_microphone
    gain_log2: 3
    keep_pipeline_alive: false
    pipeline:
      - adf_mic
      - self

media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: watch player
    keep_pipeline_alive: false
    internal: false
    pipeline:
      - self
      - adf_spk
    
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO44
  - id: i2s_out
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO48

voice_assistant:
  id: va
  microphone: adf_microphone
  media_player: adf_media_player
  noise_suppression_level: 1
  volume_multiplier: 4
  use_wake_word: false
  on_error:
    - voice_assistant.stop
 
output:
  - platform: ledc
    pin: GPIO45
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    default_transition_length: 500ms
    restore_mode: RESTORE_AND_OFF
                
color:
  - id: green
    hex: '75D15F'
  - id: red
    hex: 'FF3131'
  - id: blue
    hex: '47B7E9'
  - id: blue_drk
    hex: '085296'
  - id: amber
    hex: 'FBAB35'
  - id: lime
    hex: '20FC30'
  - id: pink
    hex: 'D92BBC'
  - id: yellow
    hex: 'FFC000'
  - id: black
    hex: '000000'
  - id: white
    hex: 'ffffff'
  - id: purple
    hex: '73264D'
  - id: text_red
    hex: 'FF3131'
  - id: text_green
    hex: '75D15F'
  - id: text_blue
    hex: '47B7E9'
  - id: text_amber
    hex: 'FBAB35'
  - id: text_lime
    hex: '20FC30'
  - id: text_pink
    hex: 'D92BBC' 
        
image:
  - file: "https://pungkula.duckdns.org:1337/local/duckie2.png"
    id: logo_img
    resize: 240x240
    type: RGB24
    

display:
  - platform: ili9xxx
    model: ST7789V
    id: screen
    transform:
      mirror_x: true
      mirror_y: true
      swap_xy: false
    dimensions:
      width: 240
      height: 240
      offset_width: 0
      offset_height: 80
    invert_colors: true
    cs_pin: 12
    dc_pin: 38
    pages:
      - id: home_page
        lambda: |-
          it.image(0, 0, id(logo_img));
          
touchscreen:
  - platform: ft63x6
    interrupt_pin: 
      number: GPIO16
      # allow_other_uses: true
    address: 0x38
    display: screen
    id: tscreen
    i2c_id: tsc
    calibration:
      x_min: 0
      x_max: 240
      y_min: 0
      y_max: 240
    on_touch:
      - voice_assistant.start 
      - media_player.play_media: http://192.168.1.8:8123/local/vad.mp3
