substitutions:
  font_glyphs: '&@!"''%()<>+=,-_.:°/$€£¥?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzÀàÁáÂâÃãÄäĀāĂăÅåǺǻẠạĄąÆæǼǽĆćĈĉČčĊċÇçĎďĐđÐðÈèÉéÊêẼẽĚěËëĒēĔĕĖėẸẹĘęĜĝǦǧĞğĠġĢģĤĥĦħıÌìÍíÎîĨĩÏïĪīĬĭİỊịĮįȷĴĵĶķĸĹĺĽľĻļŁłĿŀŃńÑñŇňŅņƝɲŊŋŉÒòÓóÔôÕõÖöŌōŎŏŐőỌọǪǫØøǾǿŒœŔŕŘřŖŗŚśŜŝŠšŞşȘșẞßŤťŢţȚțŦŧÞþÙùÚúÛûŨũÜüŪūŬŭŮůŰűỤụŲųẀẁẂẃŴŵẄẅỲỳÝýŶŷỸỹŸÿȲȳŹźŽžŻżĲĳƏə'  
esphome:
  name: waveshare-display
  friendly_name: Waveshare Display
  on_boot:
    - switch.turn_on: back_light
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
  flash_size: 16mb
psram:
  mode: octal
  speed: 80MHz
  
api:

logger:
  hardware_uart: USB_SERIAL_JTAG

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.144
ota:
  platform: esphome
  
time:

ch422g:
  - id: io_ex

i2c:
  sda: 8
  scl: 9
  frequency: 400kHz
  scan: true
  id: bus_a

touchscreen:
  - platform: gt911
    i2c_id: bus_a
    address: 0x5D
    id: device_touchscreen
    reset_pin:
      ch422g: io_ex
      number: 1
    interrupt_pin:
      number: 4

display:
  - platform: rpi_dpi_rgb
    id: device_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 800
      height: 480
    reset_pin:
      ch422g: io_ex
      number: 3
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3.
        - 2         #r4.
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3.
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

switch:
  - platform: gpio
    id: back_light
    name: Backlight
    pin:
      ch422g: io_ex
      number: 2
      mode:
        output: true
      inverted: false

button:
  - platform: restart
    id: reboot
    name: reboot

font:

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font16
    size: 16
    bpp: 4     
    glyphs:
      '${font_glyphs}'
      
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font28
    size: 28
    bpp: 4    
    glyphs:
      '${font_glyphs}'

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font40
    size: 40
    bpp: 4     
    glyphs:
      '${font_glyphs}'
   
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font18
    size: 18
    bpp: 4     
    glyphs:
      '${font_glyphs}'      
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font22
    size: 22
    bpp: 4    
    glyphs:
      '${font_glyphs}'
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font60
    size: 60
    glyphs:
      '${font_glyphs}'

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/materialdesignicons-webfont.ttf"
    id: icon_font_80
    size: 80
    bpp: 4
    glyphs: &icon_glyphs 
      - "\U000F072A" # washer
      - "\U000F0917" #dryer
      - "\U000F1B20" #desk lamp
      - "\U000F0450"#refresh
      - "\U000F0A19"#toggle off
      - "\U000F0521"#toggle on
      - "\U000F0150"#clock
      - "\U000F057E"#speaker on
      - "\U000F0581"#speaker off
      - "\U000F1322"#tools
      - "\U000F12D4"#garage open
      - "\U000F12D3"#garage closed
      - "\U000F0238"#heating
      - "\U000F0B2C"#up
      - "\U000F0B26"#down
      - "\U000F024A"#garden
      - "\U000F1987"#floods
      - "\U000F04C8"#spots
      - "\U000F1722"#fire off
      - "\U000F02DC"#home button
      - "\U000F0D90"#monitor_off
      - "\U000F0B28"#left
      - "\U000F192D"#electricity
      - "\U000F1A1B"#gas
      - "\U000F0B6C"#car battery
      - "\U000F0873"#car miles non
      - "\U000F0875"#car miles low
      - "\U000F0874"#car miles full
      - "\U000F0B2A"#right
      - "\U000F04B9"#living room
      - "\U000F1061"#dining
      - "\U000F06E8"#light bulb illuminated
      - "\U000F0335"#light bulb off
      - "\U000F07F4"#tv
      - "\U000F1160"#kitchen
      - "\U000F0210"#fan
      - "\U000F050F"#temp
      - "\U000F1747"#tall lamp
      - "\U000F0769"#ceiling
      - "\U000F18DD"#ceiling multiple
      - "\U000F091C"#wall light
      - "\U000F075A"#music 
      - "\U000F08D6"#settings
      - "\U000F036D"#microphone off  
      - "\U000F032A"#energy leaf   
      - "\U000F1B94"#sleep
      
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/materialdesignicons-webfont.ttf"
    id: icon_font_120
    size: 120
    # bpp: 4
    glyphs: *icon_glyphs

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/materialdesignicons-webfont.ttf"
    id: icon_font_60
    size: 60
    bpp: 4
    glyphs: *icon_glyphs
          

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/materialdesignicons-webfont.ttf"
    id: icon_font_40
    size: 40
    bpp: 4
    glyphs: *icon_glyphs 
     
color:
  - id: green
    hex: '75D15F'
  - id: leaf_green
    hex: '60A86A'
  - id: red
    hex: 'FF3131'
  - id: blue
    hex: '47B7E9'
  - id: blue_drk
    hex: '085296'
  - id: amber
    hex: 'FBAB35'
  - id: lime
    hex: '20FC30'
  - id: pink
    hex: 'D92BBC'
  - id: yellow
    hex: 'FFC000'
  - id: black
    hex: '000000'
  - id: white
    hex: 'ffffff'
  - id: purple
    hex: '73264D'
  - id: light_blue
    hex: '2E98DA'
  - id: lilac
    hex: 'D6BED0'
  - id: bg_blue
    hex: '032341'
  - id: bg_purple
    hex: 'A16793'
  - id: bg_green
    hex: '05350B'
  - id: bg_red
    hex: '3C0000'
  - id: bg_pink
    hex: '61034D'
  - id: bg_charcoal
    hex: '323232'
  - id: bg_brown
    hex: '41220D'
  - id: bg_grey
    hex: '4F4F4F'
lvgl:
  displays:
    - device_display
  touchscreens:
    - device_touchscreen
  theme:
    label:
      text_font: my_font28 
      text_align: CENTER
      text_color: 0xffffff
      align: TOP_MID

    button:
      bg_color: light_blue
      bg_opa: COVER
      border_color: 0x53334B
      border_width: 4
      text_color: white
      radius: 20
      shadow_color: bg_grey
      shadow_ofs_x: 0
      shadow_ofs_y: 0
      shadow_spread: 3
      shadow_width: 5
      shadow_opa: 70%
      checked: 
        bg_color: blue_drk
        bg_opa: COVER
        border_color: black
        border_width: 2
        text_color: yellow
        radius: 20
        shadow_color: yellow
        shadow_ofs_x: 0
        shadow_ofs_y: 0
        shadow_spread: 5
        shadow_width: 5
        shadow_opa: 70%

    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0xcccaca
      bg_opa: 15%
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
    image: 
      border_width: 0
        
  style_definitions:
    - id: main_content
      bg_color: light_blue
      text_color: 0xFFFFFF
      width: 100%
      height: 80%    
      align: TOP_MID
      border_width: 0
      radius: 0     

    - id: main_content_full
      bg_color: light_blue
      text_color: 0xFFFFFF
      width: 100%
      height: 100%    
      align: TOP_MID
      border_width: 0
      radius: 0
      
    - id: bottom_content_full
      bg_color: blue_drk
      text_color: white
      text_align: left
      text_font: my_font40
      align: BOTTOM_LEFT
      width: 100%
      height: 20%    
      border_side: TOP
      border_width: 6
      border_color: purple
      radius: 0       
                             

  top_layer:
      widgets:
        - obj:
            id: bottom_bar
            styles: bottom_content_full
            border_width: 0
            widgets:            
              - label:
                  id: in_temp_lvgl_icon
                  align: LEFT_MID
                  text_font: icon_font_40
                  text: "\U000F050F"
              - label:
                  id: in_temp_lvgl
                  align: LEFT_MID
                  translate_x: 40
                  translate_y: 5
                  text: " "
              - label:
                  id: heating_set_temp_lvgl_icon
                  align: LEFT_MID
                  translate_x: 150
                  text_font: icon_font_40
                  text: "\U000F0238"

              - label:
                  id: heating_set_temp_lvgl
                  align: LEFT_MID
                  translate_x: 190
                  translate_y: 5
                  text: " "

              - label:
                  id: out_temp_lvgl_icon
                  align: LEFT_MID
                  translate_x: 300
                  text_font: icon_font_40
                  text: "\U000F024A"

              - label:
                  id: out_temp_lvgl
                  align: LEFT_MID
                  translate_x: 340
                  translate_y: 5
                  text: " "

              - label:
                  id: energy_lvgl_icon
                  align: LEFT_MID
                  translate_x: 450
                  text_font: icon_font_40
                  text: "\U000F032A"

              - label:
                  id: energy_lvgl
                  align: LEFT_MID
                  translate_x: 500
                  translate_y: 5
                  text: " "

              - label:
                  id: home_lvgl
                  align: BOTTOM_RIGHT
                  text_font: icon_font_60
                  text: "\U000F02DC"

              - label:
                  id: sleep_lvgl
                  align: BOTTOM_RIGHT
                  translate_x: -75
                  text_font: icon_font_60
                  text: "\U000F1B94"

  pages:
    - id: main_page
      widgets:
        - obj: 
            styles: main_content
            layout: 
              pad_column: 10
              pad_row: 5
              type: GRID 
              grid_columns: [FR(1), FR(1), FR(1), FR(1)] 
              grid_rows: [FR(48), FR(1), FR(48), FR(17)]

            widgets:
              - button:
                  checkable: true
                  id: button_1
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: dining_light_lvgl
                        text_font: icon_font_120
                        text: "\U000F18DD"
                        align: CENTER  

              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 1 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: true
                  id: button_2
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: big_light_lvgl
                        text_font: icon_font_120
                        text: "\U000F0769"
                        align: CENTER
                          
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 1 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: true
                  id: button_3
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: back_light_lvgl
                        text_font: icon_font_120
                        text: "\U000F0769" 
                        align: CENTER
                                
              - label:
                  grid_cell_column_pos: 2 # place the widget in
                  grid_cell_row_pos: 1 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: true
                  id: button_4
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: living_room_lvgl
                        text_font: icon_font_120
                        text: "\U000F04B9"
                        align: CENTER

              - label:                        
                  grid_cell_column_pos: 3 # place the widget in
                  grid_cell_row_pos: 1 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                                   
                 
## second row ##

              - button:
                  checkable: false
                  id: button_5
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: fan_lvgl
                        text_font: icon_font_120
                        text: "\U000F0210"  
                        align: CENTER
                  
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: false
                  id: button_6
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: tall_lamp_lvgl
                        text_font: icon_font_120
                        text: "\U000F1747"  
                        align: CENTER
                   
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: false
                  id: button_7
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: wall_lamp_lvgl
                        text_font: icon_font_120
                        text: "\U000F091C"  
                        align: CENTER
                         
              - label:
                  grid_cell_column_pos: 2 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text: " "
                  text_align: CENTER                  

              - button:
                  checkable: false
                  id: button_8
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  pressed:
                    bg_color: red
                  widgets:
                    - label:
                        id: heat_boost_lvgl
                        text_font: icon_font_120
                        text: "\U000F0238"
                        align: CENTER
 