esphome:
  name: wt32-sc01 plus
  friendly_name: WT32-SC01 PLUS
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    platform_version: 6.9.0
    version: 5.3.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

psram:
  mode: quad
  speed: 80MHZ

external_components:
  - source: github://clydebarrow/esphome@i8080
    components: [ io_bus, i80 ]
    refresh: 1h
  - source: github://pr#6537
    components: [ spi, ili9xxx ]
    refresh: 1h

ota: 
  - platform: esphome 

api:
  on_client_connected:
    - script.execute: backlight_off
logger:
  hardware_uart: USB_SERIAL_JTAG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO6
  scl: GPIO5
  id: touch_i2c
  
touchscreen:
  - platform: ft63x6
    id: device_touchscreen
    interrupt_pin: GPIO7
    transform:
      swap_xy: true
      mirror_x: true
    on_touch:
      - script.execute: backlight_off

i80:
  - id: i80bus
    dc_pin: 
      number: GPIO0
      ignore_strapping_warning: true
    wr_pin: GPIO47
    data_pins:
      - GPIO9
      - number: GPIO46
        ignore_strapping_warning: true
      - number: GPIO3
        ignore_strapping_warning: true
      - GPIO8
      - GPIO18
      - GPIO17
      - GPIO16
      - GPIO15

display:
  - platform: ili9xxx
    id: device_display
    model: ST7796
    bus_type: i80
    reset_pin: GPIO4
    pixel_mode: 16bit
    color_order: bgr
    invert_colors: true
    dimensions:
      width: 480
      height: 320
    transform:
      swap_xy: true
    auto_clear_enabled: false

output:
  - platform: ledc
    id: backlight_pwm
    pin:
      number: GPIO45
      ignore_strapping_warning: true

light:
  - platform: monochromatic
    id: backlight
    output: backlight_pwm
    restore_mode: ALWAYS_ON
